### ISSUE TITLE
Brisbane City Council: No data received since 30 Jul 2020

### ISSUE THREAD

**Issue by mlandauer** [planningalerts-scrapers/issues#178]
This issue has been **automatically** created by PlanningAlerts for [Brisbane City Council](http://www.planningalerts.org.au/authorities/brisbane)

It uses the scraper [planningalerts-scrapers/multiple_masterview](https://morph.io/planningalerts-scrapers/multiple_masterview)

Only close this issue once the authority is working again on PlanningAlerts. Otherwise a new issue will just automatically created. Also, if there is a duplicate issue close the other one in favour of this one.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_323ph)

**Comment by mlandauer** [comment]
Looks like they have an entirely new system. Sigh.... They're calling it "development.i". Looks like it will need a new scraper

**Comment by katska** [comment]
I spoke with someone at Brisbane Planning, to ask if they would consider releasing as open data. Turns out they're using a layer of code (Development.i turns out to have been written over at Sunshine Coast council) and sits over the top of their data that 'copies what planningalerts does' but includes more fields of information. I didn't receive any indication that's under serious consideration to either expose the original data again or open the data through their Development.i system. Sunshine Coast on the other hand are still allowing access through their original system/URL and are providing the ability to sign up from their site in addition.

**Comment by shangzhipan** [comment]
I've had a look into the new system and it seems they have a post endpoint that returns a JSON object with all the data. No need for html parsing anymore: https://developmenti.brisbane.qld.gov.au/Geo/GetApplicationFilterResults 

I will be starting to work on a morph.io application next week.

**Comment by katska** [comment]
@shangzhipan  any luck?

**Comment by shangzhipan** [comment]
@katska Yeah, I made great progress and have all data loaded and formatted. I just need to add a paging functionality to load all applications in case there are more than the supported max limit of 200 per request. Hope, I can finish it this weekend and send it off to planning alerts for integration.

**Comment by shangzhipan** [comment]
@katska finished and sent off to the planning alerts team. Hope to get a reply soon.
