### ISSUE TITLE
Councillor data is out of date

### ISSUE THREAD

**Issue by jamezpolley** [planningalerts-scrapers/issues#38]
Launceston Council has had an election and needs to be udpated.

Councillor information is at https://github.com/openaustralia/planningalerts#adding-councillors-for-an-authority

Procedure for updating Popolo repository is at https://github.com/openaustralia/planningalerts#adding-councillors-for-an-authority

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iq8l)

**Comment by mlandauer** [comment]
A while ago we decided that we couldn't keep up with all the councillor changes that were happening across the country. It was just too much. After all there are over 250 authorities on PlanningAlerts alone and a good 10 or so councillors so that's 2500 people or so to keep up to date. Way out of what we can achieve on our own.

So, I'm going to close this.

I think of course we should revisit this if we come up with a good way to keep the information up to date.
