### ISSUE TITLE
Add Northern Territory DAs

### ISSUE THREAD

**Issue by katska** [planningalerts-scrapers/issues#384]
Northern Territory 
Population 246,500

The DAs on notice are here:
https://www.ntlis.nt.gov.au/planning-notices-online/notices#/

**Comment by katska** [comment]
I'm guessing its a custom one

**Comment by mlandauer** [comment]
We are already collecting DAs for NT from the Northern Territory Lands Group https://www.planningalerts.org.au/authorities/northern_territory/applications

Are these other ones you found the same or in addition to or what exactly?

**Comment by kat** [comment]
hmm no I think some kind of brain freeze, I thought it was broken, but looks like we're collecting them. Sorry!

—
Katherine Szuminska

--- original message ---
On May 20, 2021, 9:33 AM GMT+10 ***@***.*** wrote:



We are already collecting DAs for NT from the Northern Territory Lands Group https://www.planningalerts.org.au/authorities/northern_territory/applications

Are these other ones you found the same or in addition to or what exactly?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---
